a = int(input("Enter First number: "))
b = int(input("Enter Second number: "))
a += b
print("After += :", a)
a -= b
print("After -= :", a)
a *= b
print("After *= :", a)
a //= b
print("After //= :", a)
a %= b
print("After %= :", a)
a += b
print("After += :", b)
a -= b
print("After -= :", b)
a *= b
print("After *= :", b)
a //= b
print("After //= :", b)
a %= b
print("After %= :", b)