a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
print("a & b =", a & b)
print("a | b =", a | b)
print("a ^ b =", a ^ b)
print("~a =", ~a)
print("a >> 1 =", a >> 1)
print("a << 1 =", a << 1)